Add requests
Lilithness/practice- pull request #2
Opened 2021-11-15 12:55 UTC by Lilithness

Use requests library to fetch a DNA sequence, and look up the mutation's symbol in Ensembl.

2021-11-15 13:15 UTC, corvus-sapiens commented on functions.py
> +    r =requests.get(url, headers={ "Content-Type" : "text/plain"})
Can you please check if Ensembl API offers the FASTA format?

2021-11-15 15:51 UTC, corvus-sapiens requested changes

2021-11-15 15:51 UTC, corvus-sapiens commented on functions.py
> +        file.write(sequence)
This can be a one-liner

2021-11-15 15:51 UTC, corvus-sapiens commented on functions.py
> +    dna = ''.join(temp[1:])
Why not use list comprehension syntax?)

2021-11-15 15:51 UTC, corvus-sapiens commented on functions.py
> +    dna = ''.join(temp[1:])
Also, this is definitely the case to use Biopython, -- but let us not add that dependency just yet.

2021-11-15 16:12 UTC, corvus-sapiens commented on functions.py
>      dna = ''.join(temp[1:])
This, again, can be a one-liner. And also, put a comment explaining why we need that slicing here, please.

2021-11-18 18:47 UTC, Lilithness commented
Use requests to query Ensembl API for the gene sequence and summary metadata

2021-11-18 18:47 UTC, merged